CREATE TABLE Users
(
    Id INT IDENTITY(1,1) PRIMARY KEY,
    Username NVARCHAR(50) NOT NULL UNIQUE,
    Email NVARCHAR(255) NOT NULL UNIQUE,
    PasswordHash NVARCHAR(255) NOT NULL,
    CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);

CREATE TABLE ChatRooms
(
    Id INT IDENTITY(1,1) PRIMARY KEY,
    Name NVARCHAR(100) NOT NULL UNIQUE,
    CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);

CREATE TABLE Messages
(
    Id INT IDENTITY(1,1) PRIMARY KEY,
    RoomId INT NOT NULL,
    UserId INT NOT NULL,
    MessageText NVARCHAR(MAX) NULL,
    FileUrl NVARCHAR(1000) NULL,
    FileName NVARCHAR(255) NULL,
    CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    CONSTRAINT FK_Messages_Room FOREIGN KEY (RoomId) REFERENCES ChatRooms(Id),
    CONSTRAINT FK_Messages_User FOREIGN KEY (UserId) REFERENCES Users(Id)
);

INSERT INTO ChatRooms
    (Name)
SELECT 'general'
WHERE NOT EXISTS (SELECT 1
FROM ChatRooms
WHERE Name = 'general');